# Problem 96 - Sudoku

https://projecteuler.net/problem=96

Inspiration for the solution from:

https://www.youtube.com/watch?v=G_UYXzGuqvM

In [27]:
import numpy as np

def isPossible(y,x,n,sudoku):
    '''Check wether n is a possible solution in position (x,y)'''
    # Check row
    for i in range(9):
        if sudoku[y][i] == n:
            return False
    # Check column
    for j in range(9):
        if sudoku[j][x] == n:
            return False
    # Check local 3x3 box
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(3):
        for j in range(3):
            if sudoku[y0+j][x0+i] == n:
                return False
    return True

def solveSudoku(sudoku):
    '''Solve recursively with backtracking'''
    for y in range(9):
        for x in range(9):
            if sudoku[y][x]==0: # found empty slot
                for n in range(1,10): # try all possible solution
                    if isPossible(y,x,n,sudoku): # if valid given the rest of the grid, set value
                        sudoku[y][x] = n
                        # try solve with newly filled slot using recursion
                        if solveSudoku(sudoku):
                            return True
                        # backtrack if recursed solution not valid
                        sudoku[y][x] = 0
                return False
    return True

In [28]:
sudoku=[
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]

sudoku = np.array(sudoku)

solveSudoku(sudoku)

print(sudoku)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [29]:
with open("data/p096_sudoku.txt") as f:
    lines = [ l.strip("\n") for l in f.readlines() ]

grids = []
for i in range(50):
    grid = []
    for j in range(10):
        if j==0:
            pass
        else:
            grid.append([int(l) for l in list(lines[i*10+j])])
    grids.append(grid)

In [31]:
sudoku = np.array(grids[0])
print(sudoku)
solveSudoku(sudoku)
print(sudoku)

[[0 0 3 0 2 0 6 0 0]
 [9 0 0 3 0 5 0 0 1]
 [0 0 1 8 0 6 4 0 0]
 [0 0 8 1 0 2 9 0 0]
 [7 0 0 0 0 0 0 0 8]
 [0 0 6 7 0 8 2 0 0]
 [0 0 2 6 0 9 5 0 0]
 [8 0 0 2 0 3 0 0 9]
 [0 0 5 0 1 0 3 0 0]]
[[4 8 3 9 2 1 6 5 7]
 [9 6 7 3 4 5 8 2 1]
 [2 5 1 8 7 6 4 9 3]
 [5 4 8 1 3 2 9 7 6]
 [7 2 9 5 6 4 1 3 8]
 [1 3 6 7 9 8 2 4 5]
 [3 7 2 6 8 9 5 1 4]
 [8 1 4 2 5 3 7 6 9]
 [6 9 5 4 1 7 3 8 2]]


In [32]:
s = 0
i = 1
print("Solving Sudokus...")
for g in grids:
    sudoku = np.array(g)
    print("Grid",i,"...",end=" ")
    solveSudoku(sudoku)
    print("done")
    s += int("".join([str(i) for i in sudoku[0][:3]]))
    i+=1
    #print(sudoku)
print(s)

Solving Sudokus...
Grid 1 ... done
Grid 2 ... done
Grid 3 ... done
Grid 4 ... done
Grid 5 ... done
Grid 6 ... done
Grid 7 ... done
Grid 8 ... done
Grid 9 ... done
Grid 10 ... done
Grid 11 ... done
Grid 12 ... done
Grid 13 ... done
Grid 14 ... done
Grid 15 ... done
Grid 16 ... done
Grid 17 ... done
Grid 18 ... done
Grid 19 ... done
Grid 20 ... done
Grid 21 ... done
Grid 22 ... done
Grid 23 ... done
Grid 24 ... done
Grid 25 ... done
Grid 26 ... done
Grid 27 ... done
Grid 28 ... done
Grid 29 ... done
Grid 30 ... done
Grid 31 ... done
Grid 32 ... done
Grid 33 ... done
Grid 34 ... done
Grid 35 ... done
Grid 36 ... done
Grid 37 ... done
Grid 38 ... done
Grid 39 ... done
Grid 40 ... done
Grid 41 ... done
Grid 42 ... done
Grid 43 ... done
Grid 44 ... done
Grid 45 ... done
Grid 46 ... done
Grid 47 ... done
Grid 48 ... done
Grid 49 ... done
Grid 50 ... done
24702
